### PR TITLE
Added a sample Dockerfile to Dockerize running bgp producer

### PR DESCRIPTION
**Pull request by Srijan-SS02**
Hey @romain-fontugne this is a sample Dockerfile I made to better align on what needs to be done. Is this how you are looking to dockerize the bgp producers or am I missing something ?

PS: This PR is not ready to be merged yet

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks, yes this is going into the right direction. Now we need to make a few things configurable.
The collector (rrc10) and if possible the crontab values  (e.g. 25 3 * * *) should be given by the user. We are using about 20 different collectors so we'll have to run 20 containers in parallel.

**Comment by ritikBhandari** [comment]
```
ENV CRONTAB_RIBS "25 3 * * "
ENV CRONTAB_UPDATES "/15 * * * *"
ENV COLLECTOR "rrc10"

RUN crontab -l | { cat; echo "$CRONTAB_RIBS python3 /home/romain/Projects/perso/kafka-toolbox/bgp/producers/bgpstream2.py -t ribs --collector $COLLECTOR"; } | crontab -
RUN crontab -l | { cat; echo "$CRONTAB_UPDATES python3 /home/romain/Projects/perso/kafka-toolbox/bgp/producers/bgpstream2.py -t updates --collector $COLLECTOR"; } | crontab -

CMD ["cron", "-f"]
```
Adding this to the codebase should help. Ofcourse it's your wish if you want to run the process in foreground mode or background. Use the `-f` flag accordingly!

**Comment by Srijan-SS02** [comment]
Thanks @ritikBhandari i'll surely consider it.

**Comment by romain-fontugne** [comment]
@ritikBhandari we have to run this for about 20 different collectors/cron values. what do you think is the best?
- we create 20ish dockerfile with the parameters hardcoded in it?
- we create one generic dockerfile, and let the user set the cron/collector values, but then we also need a config file somewhere to list of values

**Comment by ritikBhandari** [comment]
@romain-fontugne with the second approach, are we trying to run all the containers and producers in parallel?
Because I think we should let the end user of the image have the authority to select which individual container or producer he/she may want for his utility?

**Comment by Srijan-SS02** [comment]
@romain-fontugne  @ritikBhandari  as far as I understand this,  we need to have **one** Dockerfile in whole Kafka-toolbox repo and there will be **20 services** in parallel. Am I getting it right??

**Comment by ritikBhandari** [comment]
@Srijan-SS02 yess. We want 20 services in parallel but not working simultaneously. We want image users to have a liberty of which container or producer to start according to their need.

What do you think @romain-fontugne ?

**Comment by Srijan-SS02** [comment]
@ritikBhandari @romain-fontugne  can you please give me some resources regarding how to give this liberty to user, it will be really helpfull.

**Comment by Srijan-SS02** [comment]
> @romain-fontugne with the second approach, are we trying to run all the containers and producers in parallel? Because I think we should let the end user of the image have the authority to select which individual container or producer he/she may want for his utility?
> 
> And as far as parameters are concerned, we can still let the user enter their preferred crontab values in each dockerfile. But just the matter of fact is that creating individual docker container images let us get more control on the containers, but if we create a generic file, if something happens to one of the container configurations, we'll have to make changes in the whole docker-compose file which can have its consequences on the whole docker-compose file.
> 
> That's the only thing to address.
> 
> In approach 1: We'll have to create individual container files. That can be a little chaos while creating. But that's the only issue. In approach 2: If there's some issue, we'll have to make the changes in the whole docker-compose file and make sure it isn't affected by the changes in the individual services. That's the only issue here.
> 
> We will have to make a decision taking into consideration the fact that the people managing these systems after GSOC should not get intimidated by complexity. Though someone who manages them will still have the required knowledge, but it is our duty to make things easier for people managing it.

@ritikBhandari  @romain I believe that the 1st approach will be good to go with, for future maintenance as well. Having dockerfile for each directory will be easier to maintain.

**Comment by romain-fontugne** [comment]
We are going to run the 20 containers in parallel (that's only for the bgp producer), this repo contains other producer/consumers that will have  a different dockerfile. 

The python scripts are currently all running on the same machine, but that would be nice if have more flexibility and we can share the load across multiple machines.

If you both prefer the 1st approach then let's go with that!

@ritikBhandari also raised a good point, we want to make it as simple as possible.

**Comment by ritikBhandari** [comment]
> We are going to run the 20 containers in parallel (that's only for the bgp producer), this repo contains other producer/consumers that will have a different dockerfile.
> 
> The python scripts are currently all running on the same machine, but that would be nice if have more flexibility and we can share the load across multiple machines.
> 
> If you both prefer the 1st approach then let's go with that!
> 
> @ritikBhandari also raised a good point, we want to make it as simple as possible.

@romain-fontugne Okay I thought we are going to run all the producers and consumers in this repo also as individual. Now understood.

So hosting them on different servers is also easy if we make it as a docker compose file. That can be taken care of.

But my question is, why do we want 20 containers for `bgp producer` directory? I can only see 3 producers there. Am I missing something?

**Comment by romain-fontugne** [comment]
Each bgp producer gets bgp data from the internet and push it to Kafka. And we have about 20 different bgp data collection point we get data from. I want to have separate bgp producer processes because sometime a bgp collector can get stuck or reply slowly, and i don't want this to impact the other producers

**Comment by romain-fontugne** [comment]
Now back to the original question:
Shall we make a docker file for each collector,  or a generic docker file. I think I initially missed the point that with the generic approach we can have a docker-compose file that contains the whole configuration (collector name, Cron values). Which is pretty good too

**Comment by ritikBhandari** [comment]
> Now back to the original question:
> Shall we make a docker file for each collector,  or a generic docker file. I think I initially missed the point that with the generic approach we can have a docker-compose file that contains the whole configuration (collector name, Cron values). Which is pretty good too 

@romain-fontugne yes that is what I mentioned earlier in our slack message and above discussion. We can do that as well.

But also another problem what we can encounter is, if we do it with a docker-compose file, container orchestration would have to be done by Docker Swarm and not Kubernetes.

And Docker Swarm is a better when we want to host multiple containers on a single host because it provides less flexibility in terms of distributed computing.
Kubernetes is the one which is more flexible.

Plus it would be easier to collect each container logs (application and system level) using Fluentd driver and visualize the health of the containers using Grafana if they are individually hosted.

But ya, it's about what is easy to do.
Not that we cannot do a docker compose file. Infact docker compose would be much easy to build, but relatively difficult to scale due to everything coupled together.

**Comment by ritikBhandari** [comment]
@romain-fontugne so just a final thing to address is:

If you think scaling of these producers and consumers would be required in near future and we need them to be available as long as possible, I'll go with individual docker files.

If yoh think scaling is not an issue and we have a buffer of time if something goes wrong, then I'll surely go with docker-compose.

**Comment by pjflux2001** [comment]
Hey, everyone! 
I would recommend we do something like this with docker-compose :
````````
version: '3'

services:
  app1:
    image: myapp:latest
    environment:
      CONFIG_FILE: /app/config1.yaml
    volumes:
      - ./config1.yaml:/app/config1.yaml

  app2:
    image: myapp:latest
    environment:
      CONFIG_FILE: /app/config2.yaml
    volumes:
      - ./config2.yaml:/app/config2.yaml
````````
This way we can manage 20 producer (bgp) containers + other containers through a single file. User can always edit the config file to have custom changes - we can merge all the config files together to provide ease of managing (if required).

Secondly, about sharing the load across multiple containers - we don't need to use an orchestration environment (as health of the container itself isn't getting affected). A simple load balancer (that too can be included in docker-compose) can be used, with service-discovery (as / if required). 

I would be more than happy to structure the suggested architecture :smile:

**Comment by ritikBhandari** [comment]
Thanks for the input @pjflux2001 
@romain-fontugne already suggested this exact idea and it's a good thought though.

But this specific repo is not the only thing we have to containerize. So we were planning to use Kubernetes at the organizational level. With that notion in mind, when u already have a Kubernetes architecture at place, it makes little sense to me to use a different load balancer when u have a default service itself.

**Comment by ritikBhandari** [comment]
Also, I didn't get ur point of container health itself not getting affected.

- Service Failure: if a producer service fails to produce messages or a consumer service fails to consume messages.

- Network Issues: If a consumer service is not able to connect to a producer service, it may not be able to consume messages

- Dependency Issues: if a producer service depends on a database that is not available, it may not be able to produce messages

- Resource Constraints: We obviously know this one.

So there can be instances where these can affect the services.

**Comment by pjflux2001** [comment]
If we don't have any other use-cases, it would be excessive to use Kubernetes solely for container replica count and load balancing. However, a more informed decision could be made by @romain-fontugne. Load balancing, health checks, and conditional restarts can be easily achieved, without dealing with the overhead of K8s. If managing the complexity, overhead and moving parts involved is worthwhile, I am all for it.

@ritikBhandari, changes that are meant to persist should always be made through files that can be mounted inside containers. Making on-the-fly changes can lead to eventual state.

Slow or unresponsive applications do not impact the overall health of the container, including its networking, storage, and processes. The container or application itself would not address the problems or failures mentioned earlier since the checks would fail alongside the application or container. To guarantee the health and connectivity of various services, a more resilient system like Icinga or Zabbix would be required outside the monitored setup.

**Comment by ritikBhandari** [comment]
> If we don't have any other use-cases, it would be excessive to use Kubernetes solely for container replica count and load balancing. However, a more informed decision could be made by @romain-fontugne. Load balancing, health checks, and conditional restarts can be easily achieved, without dealing with the overhead of K8s. If managing the complexity, overhead and moving parts involved is worthwhile, I am all for it.
> 
> @ritikBhandari, changes that are meant to persist should always be made through files that can be mounted inside containers. Making on-the-fly changes can lead to eventual state drift.
> 
> Slow or unresponsive applications do not impact the overall health of the container, including its networking, storage, and processes. The container or application itself would not address the problems or failures mentioned earlier since the checks would fail alongside the application or container. To guarantee the health and connectivity of various services, a more resilient system like Icinga or Zabbix would be required outside the setup.

True @pjflux2001 
Overhead of K8S would be expensive if we are using it solely for the purpose of this repo. That is why I mentioned that I was planning to use it on an organizational level for major containers and for that reason, it didn't make much sense to keep it isolated with other services.

Regarding checks, similar to the state that we don't have K8S right now, we also don't have automated checks and tests as of now. So that is also dependent on whether we use it or not in future.

@romain-fontugne I would suggest to go with a docker-compose file for now as to keep things simple. Usage of K8S and other technologies is more based on who is leading the project in GSOC. So that can be thought-upon later.

**Comment by pjflux2001** [comment]
@ritikBhandari The overhead remains the same regardless of how many repos you do with it! There's lot more things to configure and manage - and not worth in case we don't use / need the other features. 

Also, the checks do not have any dependency with k8s.

**Comment by ritikBhandari** [comment]
@pjflux2001 i never said they have any dependency with k8s lol.
What I said is we dont have automated tests as of now

**Comment by pjflux2001** [comment]
> So that is also dependent on whether we use it or not in future.

@ritikBhandari maybe you weren't a lot clear here

**Comment by ritikBhandari** [comment]
@pjflux2001 actually it's not abour being clear here. 
Actually it's meant to be a GSOC project implementation. So everyone has their own thought process and design choices that will be ultimately selected by the IHR committee.
That is why I said having tests and builds is also dependent on whether we use it or not, which will be eventually decided by IHR members.

Hope I was able to give a little context here.

**Comment by ritikBhandari** [comment]
> @pjflux2001 
> Actually it's meant to be a GSOC project implementation. So everyone has their own thought process and design choices that will be ultimately selected by the IHR committee.
> That is why I said having tests and builds is also dependent on whether we use it or not, which will be eventually decided by IHR members.
> 
> Hope I was able to give a little context here.

@pjflux2001 
https://github.com/InternetHealthReport
This whole repo has to be containerized where we have multiple backend and frontend components. These itself have several smaller components within.

This is the total plan and this kafka-toolbox repo is a part of a bigger plan.
That is why we also have to see it from a macro-perspective as well.

Maybe I'm being a little clear from here-on😂

**Comment by ritikBhandari** [comment]
Very true @romain-fontugne  
The bigger problem is not these individual containers but the design choices for the entire project. 

Your proposal for the current implementation seems apt at this time.

**Pull request closed without merging**
